In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import datetime

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

import os

pd.set_option('display.max_columns', 500)

1. ¿cuál es el PROBLEMA que queremos resolver? (de aquí saldrán las hipótesis y objetivos, entre más detalle mejor)

Se puede determinar cuanto tiempo va a jugar una persona con los valores de los datos?
Objetivo.- Visualizar los factores mas importantes para que un juego sea jugado por mucho tiempo

2. ¿cuál sería el RESULTADO ESPERADO del análisis? (aquí hay que pensar en ingeniería inversa; del resultado esperado, definiendo cada módulo que me hará llegar a ese resultado, hasta el planteamiento del problema, que es donde inicia el proyecto)

Esperamos observar varios juegos online o sin historia como aquellos con mas tiempo jugado. Ademas, estos juegos pertenecen a una empresa grande. 

3. ¿CÓMO pienso resolverlo? (QUÉ voy a ocupar y CÓMO pienso usarlo)

Mucha limpieza de datos
Regresion

In [3]:
df_steam = pd.read_csv('steam-store-games/steam.csv')
df_steam = df_steam[df_steam['average_playtime'] > 0]
df_steam.drop(['english', 'required_age'], axis=1, inplace=True)

In [4]:
dates = df_steam['release_date'].map(lambda x:x.split('-'))
df_steam['year'] = dates.map(lambda x:x[0])
df_steam['month'] = dates.map(lambda x:x[1])
df_steam.drop('release_date', axis=1, inplace=True)

In [5]:
df_steam['rating'] = df_steam['positive_ratings'] / (df_steam['positive_ratings'] + df_steam['negative_ratings']) * 100
df_steam['rat_count'] = df_steam['positive_ratings'] + df_steam['negative_ratings']
df_steam.drop(['positive_ratings', 'negative_ratings'], axis=1, inplace=True)

In [6]:
owners = ['0-20000', '20000-50000', '50000-100000', '100000-200000', '200000-500000', '500000-1000000', '1000000-2000000', '2000000-5000000', '5000000-10000000', '10000000-20000000', '20000000-50000000', '50000000-100000000', '100000000-200000000']
bucket_own = dict([(a, 1) for a in owners[:5]] + [(a, 2) for a in owners[5:9]] + [(a, 3) for a in owners[9:]])
df_steam.owners = df_steam.owners.replace(bucket_own)

In [7]:
df_steam['linux'] = df_steam.platforms.map(lambda x:x.find('linux') >= 0)
df_steam['mac'] = df_steam.platforms.map(lambda x:x.find('mac') >= 0)
df_steam.drop('platforms', axis=1, inplace=True)

In [22]:
def extract_relevant_words(feature):
    min_samples = 5
    all_words = []
    for word in df_steam[feature].map(lambda x:x.split(';')):
        all_words += word
    all_words = pd.Series(all_words)
    all_words = all_words.value_counts() > min_samples
    all_words = all_words[all_words == True]
    return all_words

In [9]:
all_dev = extract_all_words('developer')
all_pub = extract_all_words('publisher')
all_cat = extract_all_words('categories')
all_gen = extract_all_words('genres')
all_tag = extract_all_words('steamspy_tags')

In [21]:
abc = all_dev.value_counts() > min_samples
abc = abc[abc == True]
len(abc)

127

In [10]:
df_steam.head(3)

,appid,name,developer,publisher,categories,genres,steamspy_tags,achievements,average_playtime,median_playtime,owners,price,year,month,rating,rat_count,linux,mac
0,10,Counter-Strike,Valve,Valve,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,17612,317,3,7.19,2000,11,97.388815,127873,True,True
1,20,Team Fortress Classic,Valve,Valve,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,277,62,2,3.99,1999,04,83.978740,3951,True,True
2,30,Day of Defeat,Valve,Valve,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,187,34,2,3.99,2003,05,89.564761,3814,True,True

In [11]:
df_steam.describe(percentiles=[.05, .25, .5, .75, .95])

,appid,achievements,average_playtime,median_playtime,owners,price,rating,rat_count
count,6.170000e+03,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000,6.170000e+03
mean,4.000430e+05,46.662723,657.369368,640.918476,1.176013,7.472110,73.824814,5.039625e+03
std,2.064139e+05,276.124639,3783.666030,4898.936256,0.392185,8.503212,17.705728,4.678293e+04
min,1.000000e+01,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000e+00
5%,2.218900e+04,0.000000,4.000000,4.000000,1.000000,0.000000,39.034191,3.100000e+01
25%,2.659500e+05,0.000000,77.000000,77.000000,1.000000,1.590000,63.165967,1.640000e+02
50%,3.887050e+05,15.000000,222.000000,228.000000,1.000000,4.990000,77.777778,5.530000e+02
75%,5.395950e+05,35.000000,365.000000,371.000000,1.000000,10.990000,87.953881,2.142500e+03
95%,7.605385e+05,90.000000,1931.100000,1611.500000,2.000000,24.990000,95.415466,1.591790e+04
max,1.051310e+06,5000.000000,190625.000000,190625.000000,3.000000,114.990000,100.000000,3.046717e+06

In [12]:
df_description = pd.read_csv('steam-store-games/steam_description_data.csv')['short_description']
df_description.head()

0    Play the world's number 1 online action game. ...
1    One of the most popular online action games of...
2    Enlist in an intense brand of Axis vs. Allied ...
3    Enjoy fast-paced multiplayer gaming with Death...
4    Return to the Black Mesa Research Facility as ...
Name: short_description, dtype: object